### ISSUE TITLE
XMLHttpRequest properties instead of GET parameters

### ISSUE THREAD

**Issue by hieronx** [jokade/scalajs-angulate#68]
At the moment, setting `HttpConfig` properties and using this as part of a `$http` request will cause them to be added to the request as GET parameters.

For example, this code:

``` scala
val host = "http://localhost:8080"
val config = HttpConfig("withCredentials" -> true)

def findAll(): HttpPromise[js.Array[Group]] = $http.get(s"$host/groups", config)
```

Sends the following GET request:

```
http://localhost:8080/groups?withCredentials=true
```

However, the `withCredentials` boolean should be enabled as a property on the [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) object, not sent along as a GET parameter.

**Comment by jokade** [comment]
Hmm, the `HttpConfig` object is passed on unmodiifed to AngularJS; have you checked what happens in "pure" AngularJS when you pass `withCredentials` to `$http.get()`?

**Comment by hieronx** [comment]
You're absolutely right, the effect of passing `withCredentials` to `HttpConfig` does not seem to be the same as setting `$httpProvider.defaults.withCredentials`, which does work for me in plain AngularJS.

However, I cannot seem to get the defaults setting to work, even after pulling _0.2.1_ which includes the `defaults.withCredentials` addition. I tried the following code:

``` scala
$httpProvider.defaults.withCredentials = true
$httpProvider.defaults.xsrfCookieName = "something"
```

While compiling, this returns the following error messages:

``` scala
[error] App.scala:23: value withCredentials is not a member of biz.enef.angulate.core.HttpDefaults
[error]       $httpProvider.defaults.withCredentials = true
[error]                              ^
[error] App.scala:24: value xsrfCookieName_= is not a member of biz.enef.angulate.core.HttpDefaults
[error]       $httpProvider.defaults.xsrfCookieName = "something"
[error]                              ^
```

I've purposefully added the `xsrfCookieName` setting, to ensure that I am actually using the latest version and it's not just the `withCredentials` flag that's not working.

Any idea why this isn't working?

**Comment by jokade** [comment]
Sorry, my fault: I declared the properties in HttpDefaults to be `def`s instead of `var`s... I'll publish a corrected snapshot.

**Comment by jokade** [comment]
@offerijns could you please check if it works with 0.2.2-SNAPSHOT?

**Comment by hieronx** [comment]
Absolutely, checking now!

**Comment by hieronx** [comment]
It works perfectly now, thanks!
